name: Production Deployment Workflow
on:
  pull_request:
    branches:
      - production
    types: [closed]
    
jobs:
  production-deployment:
    uses: CondeNast/astrocloud-workflow/.github/workflows/production_deployment.yml@main
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      success_slack_webhook_url: ${{ secrets.SUCCESS_SLACK_WEBHOOK_URL }}
      failure_slack_webhook_url: ${{ secrets.FAILURE_SLACK_WEBHOOK_URL }}
      prod_astrocloud_key_id: ${{ secrets.PROD_ASTROCLOUD_KEY_ID }}
      prod_astrocloud_key_secret: ${{ secrets.PROD_ASTROCLOUD_KEY_SECRET }}