name: Stale Branches Deletion Workflow
on:
  schedule:
    - cron: 0 3 * * 0,4,5,6
jobs:
  stale-branches-deletion:
    if: github.repository != 'CondeNast/astrocloud-template'
    uses: CondeNast/astrocloud-workflow/.github/workflows/stale_branches_deletion.yml@main
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      success_slack_webhook_url: ${{ secrets.SUCCESS_SLACK_WEBHOOK_URL }}
      failure_slack_webhook_url: ${{ secrets.FAILURE_SLACK_WEBHOOK_URL }}